#!/bin/bash
set -e

# Lattice Orchestrator - Production Setup
# Usage: curl -fsSL https://raw.githubusercontent.com/aidenappl/lattice-api/main/deploy/setup.sh | bash

INSTALL_DIR="/opt/lattice"
REGISTRY_URL="registry.appleby.cloud"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║     Lattice Orchestrator Setup           ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Check Docker
command -v docker >/dev/null 2>&1 || {
    echo "Docker not found. Installing..."
    curl -fsSL https://get.docker.com | sh
    sudo systemctl enable docker
    sudo systemctl start docker
}
echo "Docker: $(docker --version | awk '{print $3}' | tr -d ',')"

# Check Docker Compose
docker compose version >/dev/null 2>&1 || {
    echo "Docker Compose not found. Please install Docker Compose v2."
    exit 1
}
echo "Compose: $(docker compose version --short)"

echo ""

# Create install directory
sudo mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Login to registry
echo "Logging into registry..."
if [ -n "$REGISTRY_USERNAME" ] && [ -n "$REGISTRY_PASSWORD" ]; then
    echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_URL" -u "$REGISTRY_USERNAME" --password-stdin
else
    echo "  Enter your registry.appleby.cloud credentials:"
    docker login "$REGISTRY_URL"
fi

echo ""

# Generate JWT signing key if not provided
if [ -z "$JWT_SIGNING_KEY" ]; then
    JWT_SIGNING_KEY=$(openssl rand -hex 32)
    echo "Generated JWT signing key."
fi

# Prompt for admin password if not set
if [ -z "$ADMIN_PASSWORD" ]; then
    echo -n "  Admin password: "
    read -r ADMIN_PASSWORD
fi

# Prompt for API URL
if [ -z "$PUBLIC_API_URL" ]; then
    echo -n "  Public API URL (e.g. https://lattice-api.appleby.cloud): "
    read -r PUBLIC_API_URL
fi

if [ -z "$ALLOWED_ORIGINS" ]; then
    echo -n "  Web app URL (e.g. https://lattice.appleby.cloud): "
    read -r ALLOWED_ORIGINS
fi

echo ""

# Write env file
sudo tee "$INSTALL_DIR/.env" > /dev/null <<ENVEOF
# Lattice configuration — generated by setup.sh
REGISTRY_URL=${REGISTRY_URL}
DB_ROOT_PASSWORD=$(openssl rand -hex 16)
JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@lattice.local}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
PUBLIC_API_URL=${PUBLIC_API_URL}
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
API_PORT=${API_PORT:-8000}
WEB_PORT=${WEB_PORT:-3000}
ENVEOF
sudo chmod 600 "$INSTALL_DIR/.env"

# Download compose file
sudo curl -fsSL -o "$INSTALL_DIR/docker-compose.yml" \
    "https://raw.githubusercontent.com/aidenappl/lattice-api/main/deploy/docker-compose.prod.yml"

# Download migration for init
sudo mkdir -p "$INSTALL_DIR/migrations"
sudo curl -fsSL -o "$INSTALL_DIR/migrations/001_initial.sql" \
    "https://raw.githubusercontent.com/aidenappl/lattice-api/main/migrations/001_initial.sql"

# Pull images
echo "Pulling images..."
cd "$INSTALL_DIR"
sudo docker compose --env-file .env pull

# Start
echo "Starting Lattice..."
sudo docker compose --env-file .env up -d

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║     Lattice is running!                  ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "  API: http://$(hostname -I | awk '{print $1}'):${API_PORT:-8000}"
echo "  Web: http://$(hostname -I | awk '{print $1}'):${WEB_PORT:-3000}"
echo ""
echo "  Admin login:"
echo "    Email:    ${ADMIN_EMAIL:-admin@lattice.local}"
echo "    Password: (the one you set)"
echo ""
echo "  Config:     $INSTALL_DIR/.env"
echo "  Compose:    $INSTALL_DIR/docker-compose.yml"
echo ""
echo "  Commands:"
echo "    cd $INSTALL_DIR && docker compose logs -f"
echo "    cd $INSTALL_DIR && docker compose restart"
echo "    cd $INSTALL_DIR && docker compose down"
echo ""
